act_background_samples: 32
act_classes: null
act_every_sample_factor: 5
b1: 0.9
b2: 0.999
batch_size: 64
checkpoint_interval: 400
dataloader_workers: 2
debug: false
device: cuda:0
early_stopping_buffer: 2000
early_stopping_patience: 16
find_lr: false
get_acts: true
gradient_accumulation_steps: null
gradient_clipping: 1.0
lr: 0.0001
lr_lb: 0.0
lr_plateau_factor: 0.2
lr_plateau_patience: 10
lr_schedule: plateau
manual_valid_ids_file: null
max_acts_per_class: 1000
memory_dataset: false
mixing_alpha: 0.1
n_epochs: 40
n_saved_models: 1
no_pbar: true
optimizer: adam
output_folder: runs/pred_runs
plot_skip_steps: 200
pretrained_checkpoint: null
sample_interval: 400
valid_size: 200
warmup_steps: auto
wd: 0.0001
weighted_sampling_columns: null


