attribution_background_samples: 32
attributions_every_sample_factor: 5
b1: 0.9
b2: 0.999
batch_size: 256
compute_attributions: true
checkpoint_interval: 50
dataloader_workers: 2
log_level: error
device: cpu
early_stopping_buffer: 2000
early_stopping_patience: 16
find_lr: false
gradient_accumulation_steps: null
gradient_clipping: 1.0
lr: 0.00001
lr_lb: 0.0
lr_plateau_factor: 0.2
lr_plateau_patience: 10
lr_schedule: plateau
manual_valid_ids_file: null
max_attributions_per_class: 1000
memory_dataset: false
mixing_alpha: 0.1
n_epochs: 40
n_saved_models: 1
no_pbar: true
optimizer: adam
output_folder: /home/panwei/he000176/jinwen/gln/model_output/real/0.4
plot_skip_steps: 200
pretrained_checkpoint: null
sample_interval: 50
valid_size: 1200
warmup_steps: auto
wd: 0.0001
weighted_sampling_columns: null


